### ISSUE TITLE
瓜哥你不慌吗？

### ISSUE THREAD

**Issue by xiangbohua** [Dongguage/Dongguage.github.io#2]
瓜哥算是我的偶像了吧。
但是看着瓜哥最近频繁冲塔挺担心的，在这里人一旦Wakeup，就会有人说that guy was bought by foreignal force。总是就是很无脑。
总之还是希望瓜哥一切平安无事了，我想如果能加上瓜哥的vx就好了。小弟的微信

**Comment by Dongguage** [comment]
谢谢关注，才看到。已加。
